name: pci
description: A new Flutter project.

# Remove this line if you wish to publish to pub.dev
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <4.0.0" # Updated SDK constraints for Dart compatibility

dependencies:
  flutter:
    sdk: flutter

  # UI & Material Design
  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.6
  flutter_spinkit: ^5.3.0
  font_awesome_flutter: ^10.5.0
  flutter_screenutil: ^5.8.5

  # State Management
  provider: ^6.1.5
  get: ^4.6.5

  # Firebase
  firebase_auth: ^4.6.0
  firebase_core: ^2.16.0
  cloud_firestore: ^4.8.0

  # Utilities
  shared_preferences: ^2.2.0
  modal_progress_hud_nsn: ^0.5.0
  geolocator: ^13.0.2
  flutter_polyline_points: ^2.1.0
  sensors_plus: ^6.1.0
  calculus: ^0.8.0
  label_google_maps_marker: ^0.0.3
  google_maps_flutter: ^2.4.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1 # Downgraded to a compatible version

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: Poppins-SemiBold
      fonts:
        - asset: assets/fonts/Poppins-SemiBold.ttf
    - family: Poppins-Regular
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
    - family: Poppins-Medium
      fonts:
        - asset: assets/fonts/Poppins-Medium.ttf
